name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Enable Required APIs
        run: |
          gcloud services enable cloudresourcemanager.googleapis.com
          gcloud services enable monitoring.googleapis.com
          gcloud services enable logging.googleapis.com
          gcloud services enable cloudtrace.googleapis.com
          gcloud services enable cloudprofiler.googleapis.com

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/shortlet-app-image:latest ./app

      - name: Push Docker image to GCR
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/shortlet-app-image:latest

      - name: Terraform Init and Apply (State Bucket)
        working-directory: terraform/bucket
        run: |
          terraform init
          terraform apply -auto-approve || true

      - name: Terraform Init and Apply (Main Infrastructure)
        working-directory: terraform
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_location: ${{ secrets.TF_VAR_location }}
          TF_VAR_cluster_name: ${{ secrets.TF_VAR_cluster_name }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get Application URL
        id: get-output
        run: |
          echo "APPLICATION_URL=$(terraform output -raw application_url)" >> $GITHUB_ENV

      - name: Check Deployment
        run: |
          curl -I ${{ env.APPLICATION_URL }}
